Fix poll errors for meshes without vertex colors
obj.data.vertex_colors is never none so it was always proceeding leading to errors

Traceback (most recent call last):
  File "\vertex_color_master\vcm_ops.py", line 1239, in poll
    vcol_info = get_isolated_channel_ids(vcol)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\vertex_color_master\vcm_helpers.py", line 58, in get_isolated_channel_ids
    vcol_id = vcol.name
              ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'