Error running "Isolate" without vertex color
Similar to previous commit, cause to `vertex_colors` never being None.

  File \vertex_color_master\vcm_ops.py", line 1200, in execute
    iso_vcol_id = "{0}_{1}_{2}".format(isolate_mode_name_prefix, self.src_channel_id, vcol.name)
                                                                                      ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'